'use client'

export default function DisclaimerBanner() {
  return (
    <div className="no-print bg-yellow-100 border-b border-yellow-300 text-yellow-900 text-sm font-semibold text-center py-3 px-6">
      Documents generated by this tool are considered drafts and are subject to legal review before use.
    </div>
  )
}
