'use client'

export default function DisclaimerBanner() {
  return (
    <div className="no-print bg-yellow-50 border-b border-yellow-200 text-yellow-800 text-xs text-center py-2 px-6">
      Documents generated by this tool are considered drafts and are subject to legal review before use.
    </div>
  )
}
