'use client'

import { useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth, SignInButton, SignUpButton } from '@clerk/clerk-react'

const NAVY = '#032147'
const PURPLE = '#753991'
const PURPLE_DARK = '#5e2c75'

export default function AuthPage() {
  const router = useRouter()
  const { isLoaded, isSignedIn } = useAuth()

  useEffect(() => {
    if (isLoaded && isSignedIn) router.replace('/')
  }, [isLoaded, isSignedIn, router])

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <header className="bg-white border-b border-gray-200 px-6 py-4">
        <h1 className="text-xl font-bold" style={{ color: NAVY }}>
          Prelegal
        </h1>
        <p className="text-sm text-gray-500">AI-powered legal document drafting</p>
      </header>

      <main className="flex-1 flex items-center justify-center p-6">
        <div className="w-full max-w-sm">
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-8">
            <h2 className="text-xl font-bold mb-1" style={{ color: NAVY }}>
              Welcome to Prelegal
            </h2>
            <p className="text-sm text-gray-500 mb-8">
              Sign in or create an account to start drafting legal agreements with AI.
            </p>

            <div className="space-y-3">
              <SignInButton mode="modal">
                <button
                  type="button"
                  className="w-full py-2.5 text-sm font-semibold text-white rounded-md transition-colors"
                  style={{ backgroundColor: PURPLE }}
                  onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = PURPLE_DARK)}
                  onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = PURPLE)}
                >
                  Sign In
                </button>
              </SignInButton>

              <SignUpButton mode="modal">
                <button
                  type="button"
                  className="w-full py-2.5 text-sm font-semibold text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 transition-colors"
                >
                  Create Account
                </button>
              </SignUpButton>
            </div>
          </div>

          <p className="mt-6 text-center text-xs text-gray-400 px-4 leading-relaxed">
            Documents generated by this tool are considered drafts and are
            subject to legal review before use.
          </p>
        </div>
      </main>
    </div>
  )
}
